[project]
name = "r4n"
version = "0.1.0"
description = "Discord interface for the eurocore api"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.11",
    "discord-py>=2.4.0",
    "logtail-python>=0.3.3",
    "pre-commit>=4.2.0",
    "requests>=2.32.3",
]
