alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
features:
- buildpack-stack=ubuntu-22
ingress: {}
name: seal-app
region: nyc
workers:
- envs:
  - key: USER
    scope: RUN_AND_BUILD_TIME
    value: GK
  - key: EUROCORE_URL
    scope: RUN_AND_BUILD_TIME
    value: https://api.europeia.dev
  - key: DISCORD_TOKEN
    scope: RUN_AND_BUILD_TIME
    type: SECRET
    value: EV[1:M3QRru3wTwPDu59pGO1hoU/KdbWlTmHq:c9Uy+IQk3adGtArLmNu0u5DFfAkAnOUn2cRrCcYRsON3HKqa+keee59DDd18rwuNFFyXVN2Gk9msLJMKZhI0nxo+gwCwl5x5LehKrWi4VrIsN8GwRmYL3Q==]
  image:
    registry: nsupc
    registry_type: GHCR
    repository: r4n
    tag: latest
  instance_count: 1
  instance_size_slug: apps-s-1vcpu-0.5gb
  name: r4n